In [87]:

# coding: utf-8

# In[ ]:




# In[23]:

import numpy as np
import matplotlib.pyplot as plt
# %matplotlib auto
# import seaborn as sns
import random

class LogisticRegresssion:
    def __init__(self, training_data, testing_data, w_vect = None):
    
        self.training_data = training_data
        self.testing_data = testing_data
        
        # initialize w vector to 0
        self.w_vect = np.array([0.,0.,0.]).T
        
        # random two points to create a line classifying the data points
        self.point1 = [random.uniform(-1,1),random.uniform(-1,1)]
        self.point2 = [random.uniform(-1,1),random.uniform(-1,1)]
        
    def target(self,point):
        x1,y1 = self.point1
        x2,y2 = self.point2
        
        slope = (y2-y1)/(x2-x1)
        # function y = slope(x-x1) + y1
        result = slope*(point[0] - x1) + y1
        # classify whether higher or lower than the line
        if result > point[1]: return 1
        else: return -1 
        
    def output(self,point):
        # return the output y for a particular point
        return np.dot(self.w_vect,point)      
    
    def gradient(self,point, y):
        entropy = 1 + np.exp(y * np.dot(self.w_vect,point))    
        print(entropy)
        numerator = -np.multiply(y,point)
        print(numerator)
        # return gradient
        return np.divide(numerator,entropy)
    
    def train(self):
        # calculate initial ouputs
        y_vect = [self.output(point) for point in self.training_data]
        learning_rate = 0.01
        delta_w = 1
        steps = 0
        # have to have weights change less than 0.01 to stop
        while delta_w > 0.01:
            steps +=1 
            w_prev = self.w_vect.copy()
            
            # shuffling the data but keeping the link using zip
            # we require this for stochastic gradient descent to choose at random
            combined = list(zip(self.training_data, y_vect))
            random.shuffle(combined)
            self.training_data[:], y_vect[:] = zip(*combined)
        
            for i in range(len(y_vect)-1):
                gradient = self.gradient(point = self.training_data[i], y = y_vect[i])
                
                self.w_vect = self.w_vect - learning_rate * gradient
                
            # return the length of the vector \\ w_next - w_prev \\
            delta_w = np.linalg.norm(self.w_vect - w_prev)  
            print(delta_w)
        
        return steps
    
    
    def test(self):
        error = 0.
        
        for point in self.testing_data:
            real = self.output(point)
            error += np.log(1 + np.exp(-real*np.dot(self.w_vect,point))) 
        
        return error / float(len(self.training_data)) 
    
def questions(run_number, data_size):
    final_error = 0
    final_epoch = 0
    
    for i in range(run_number):
        training_data = [[1.,random.uniform(-1,1),random.uniform(-1,1)] for i in range(data_size)]
        testing_data = [[1.,random.uniform(-1,1),random.uniform(-1,1)] for i in range(data_size)]
        
        logr = LogisticRegresssion(training_data,testing_data)
        
        epochs = logr.train()
        error = logr.test()
        
        final_error += error
        final_epoch += epochs
       
    return final_error/ float(run_number), final_epoch
            


# In[ ]:





In [88]:
if __name__ == "__main__":
    print(questions(run_number=10,data_size=100))

2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  

[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0.  0.]
0.0
2.0
[-0.  0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0.  0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0. -0. -0.]
2.0
[-0.  0. -0.]
2.0
[-0.  0.  0.]
2.0
[-0. -